#!/usr/bin/env python3
"""Build the source-controlled research notebooks with nbformat.

The notebooks are generated from Python source so structural edits are reviewable.  Run
``scripts/execute_notebooks.py`` afterwards to refresh outputs in a clean kernel.
"""

from __future__ import annotations

import argparse
from pathlib import Path

import nbformat as nbf

ROOT = Path(__file__).resolve().parents[1]
NOTEBOOK_DIR = ROOT / "notebooks"


def _markdown(source: str) -> nbf.NotebookNode:
    return nbf.v4.new_markdown_cell(source.strip())


def _code(source: str) -> nbf.NotebookNode:
    return nbf.v4.new_code_cell(source.strip())


def _notebook(
    cells: list[nbf.NotebookNode],
    *,
    experiment: str,
    status: str = "synthetic_control_not_paper_evidence",
) -> nbf.NotebookNode:
    return nbf.v4.new_notebook(
        cells=cells,
        metadata={
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3",
            },
            "language_info": {"name": "python", "version": "3.11"},
            "latent_safety": {
                "experiment": experiment,
                "generated_by": "scripts/build_notebooks.py",
                "status": status,
            },
        },
    )


def _e0_notebook() -> nbf.NotebookNode:
    cells = [
        _markdown(
            r"""
# E0 — Can the proposed safety-defect measurements pass controlled tests?

**TL;DR.** On enumerated controls, the exact audit should report zero for an injective code and
recover the full planted defect for an explicit fold. A near-collision should switch only when its
pre-registered radius reaches the planted separation. Jointly scaling codes and radii should leave
the result unchanged. In contrast, the unthresholded nearest-unsafe-neighbor fraction should vary
with sample density and class balance even for an injective encoder. These are measurement gates,
not empirical evidence about trained neural networks.

This notebook is a deterministic, CPU-sized experiment log for Gate G1. It is generated by
`scripts/build_notebooks.py`; edit the generator rather than hand-editing notebook JSON.
"""
        ),
        _markdown(
            r"""
## Context, assumptions, and pass criteria

- Safety is `h(x) >= 0`; unsafe means the strict condition `h(x) < 0`.
- Every synthetic state is enumerated, so exact-code results are finite ground truth, not a
  population estimate.
- A radius is fixed before inspecting an outcome. Raw latent radii have no invariant meaning under
  rescaling, so the rescaling control transforms the radius with the code.
- The nearest-neighbor statistic is retained only to demonstrate why it cannot certify an exact
  collision.

The notebook fails loudly unless: identity defect = 0; folded defect = planted maximum; the
near-collision transition is recovered; the rescaling equality holds; and the action-conflict
fixture is detected.
"""
        ),
        _code(
            r"""
from pathlib import Path
import json
import random
import sys

import matplotlib
import matplotlib.pyplot as plt
import numpy as np
from IPython.display import Markdown, display

ROOT = Path.cwd()
if ROOT.name == "notebooks":
    ROOT = ROOT.parent
elif (ROOT / "LatentSafety" / "src").exists():
    ROOT = ROOT / "LatentSafety"
if not (ROOT / "src" / "latent_safety").exists():
    raise RuntimeError(f"Could not locate repository root from {Path.cwd()}")
sys.path.insert(0, str(ROOT / "src"))

from latent_safety.metrics.action import audit_exact_action_fibers
from latent_safety.metrics.defect import empirical_defect_curve, nearest_unsafe_diagnostic
from latent_safety.metrics.finite import audit_finite_static_fibers
from latent_safety.synthetic import make_aliasing_fixture
from latent_safety.benchmarks import (
    ObservationSpec,
    make_action_conflict_pair,
    make_static_aliasing_pair,
    reconstruct_current_velocity,
)

SEED = 20260821
random.seed(SEED)
np.random.seed(SEED)
print({
    "python": sys.version.split()[0],
    "numpy": np.__version__,
    "matplotlib": matplotlib.__version__,
    "seed": SEED,
    "repo_root": str(ROOT),
})
"""
        ),
        _markdown("## 1. Exact identity and planted-collision controls"),
        _code(
            r"""
fixture = make_aliasing_fixture(n_pairs=40, max_margin=1.0, seed=SEED)
identity_audit = audit_finite_static_fibers(fixture.faithful_latents, fixture.margins)
folded_audit = audit_finite_static_fibers(fixture.collapsed_latents, fixture.margins)

exact_rows = [
    {
        "representation": "injective control",
        "mixed_fibers": identity_audit.mixed_fiber_count,
        "collided_safe_states": identity_audit.collided_safe_count,
        "exact_defect": identity_audit.exact_defect,
    },
    {
        "representation": "explicit fold",
        "mixed_fibers": folded_audit.mixed_fiber_count,
        "collided_safe_states": folded_audit.collided_safe_count,
        "exact_defect": folded_audit.exact_defect,
    },
]
display(exact_rows)

assert identity_audit.exact_defect == 0.0
assert folded_audit.exact_defect == 1.0
assert folded_audit.mixed_fiber_count == 40
"""
        ),
        _markdown(
            r"""
## 2. A known near-collision and a scale-equivariance check

Each safe state and its unsafe partner are separated by exactly `eta` in code space; different
pairs are placed far apart. Therefore the robust witness is zero for radii below `eta` and recovers
the largest safe margin at and above `eta`. This checks the operational-radius implementation.
"""
        ),
        _code(
            r"""
eta = 0.08
pair_margins = np.linspace(0.05, 1.0, 30)
near_codes = []
near_margins = []
for index, margin in enumerate(pair_margins):
    anchor = 4.0 * index
    near_codes.extend(((anchor, 0.0), (anchor, eta)))
    near_margins.extend((float(margin), -float(margin)))

deltas = (0.0, 0.02, 0.04, 0.079, 0.08, 0.10, 0.16)
near_curve = empirical_defect_curve(near_codes, near_margins, deltas=deltas)
near_values = [point.witness_margin for point in near_curve]

scale = 7.5
scaled_codes = [tuple(scale * value for value in code) for code in near_codes]
scaled_curve = empirical_defect_curve(
    scaled_codes,
    near_margins,
    deltas=tuple(scale * delta for delta in deltas),
)
scaled_values = [point.witness_margin for point in scaled_curve]

display([
    {"delta": delta, "witness_margin": value}
    for delta, value in zip(deltas, near_values, strict=True)
])
assert all(value == 0.0 for delta, value in zip(deltas, near_values, strict=True) if delta < eta)
assert near_values[deltas.index(eta)] == 1.0
assert np.allclose(near_values, scaled_values, atol=1e-12, rtol=0.0)
"""
        ),
        _markdown(
            r"""
## 3. Why unthresholded 1-NN is only a diagnostic

All codes below are the physical scalar state itself, so the representation is injective and its
exact defect is zero. We alter only which finite samples happen to occur near the boundary. The
cross-boundary nearest-neighbor fraction moves anyway.
"""
        ),
        _code(
            r"""
def density_case(n_safe: int) -> dict[str, float | int]:
    safe = [0.001] + list(np.linspace(0.10, 1.0, n_safe - 1))
    unsafe = [-0.001] + list(-np.linspace(0.10, 1.0, n_safe - 1))
    states = safe + unsafe
    result = nearest_unsafe_diagnostic([(value,) for value in states], states)
    exact = audit_finite_static_fibers([(value,) for value in states], states)
    return {
        "safe_samples": n_safe,
        "unsafe_samples": n_safe,
        "1nn_cross_fraction": result.cross_boundary_fraction,
        "exact_defect": exact.exact_defect,
    }


def balance_case(n_unsafe: int) -> dict[str, float | int]:
    safe = [0.01] + list(np.linspace(0.05, 1.0, 49))
    unsafe = list(-np.arange(1, n_unsafe + 1) / (n_unsafe + 1))
    states = safe + unsafe
    result = nearest_unsafe_diagnostic([(value,) for value in states], states)
    exact = audit_finite_static_fibers([(value,) for value in states], states)
    return {
        "safe_samples": len(safe),
        "unsafe_samples": n_unsafe,
        "1nn_cross_fraction": result.cross_boundary_fraction,
        "exact_defect": exact.exact_defect,
    }


density_rows = [density_case(size) for size in (10, 25, 50, 100, 250)]
balance_rows = [balance_case(size) for size in (5, 10, 25, 50, 100, 250)]
display(Markdown("**Sample-density sweep**"))
display(density_rows)
display(Markdown("**Class-balance sweep**"))
display(balance_rows)

assert all(row["exact_defect"] == 0.0 for row in density_rows + balance_rows)
assert len({row["1nn_cross_fraction"] for row in density_rows}) > 1
assert len({row["1nn_cross_fraction"] for row in balance_rows}) > 1
"""
        ),
        _markdown("## 4. Dynamic/action-information control"),
        _code(
            r"""
# At their shared code, state 0 permits only action 0 and state 1 permits only action 1.
action_audit = audit_exact_action_fibers(
    latents=[(0.0,), (0.0,), (1.0,)],
    action_safety_margins=[(1.0, -1.0), (-1.0, 1.0), (0.5, 0.2)],
)
display(action_audit)

assert action_audit.individually_viable_fiber_count == 1
assert action_audit.conflicting_fiber_count == 1
assert action_audit.worst_required_violation == 1.0
"""
        ),
        _markdown(
            r"""
## 5. Partial-observability floor and history recovery

The controlled double integrator separates two failure modes analytically. A saturated position
sensor aliases a safe and unsafe state with known static witness `0.5`. Position-only observation
aliases two currently safe states with opposite hidden velocities: static labels agree, but their
one-step safe-action sets are disjoint and force violation `0.25` on the finite grid. A causal
two-position/action history reconstructs velocity exactly in the noise-free benchmark and separates
that action-conflicted pair.
"""
        ),
        _code(
            r"""
static_pair = make_static_aliasing_pair()
dynamic_pair = make_action_conflict_pair()

static_sensor_audit = audit_finite_static_fibers(
    [static_pair.left_observation, static_pair.right_observation],
    static_pair.safety_margins,
)
dynamic_static_audit = audit_finite_static_fibers(
    [dynamic_pair.left_observation, dynamic_pair.right_observation],
    dynamic_pair.safety_margins,
)
dynamic_action_audit = audit_exact_action_fibers(
    [dynamic_pair.left_observation, dynamic_pair.right_observation],
    dynamic_pair.action_safety_margins,
)

history_observer = ObservationSpec.position_action_history(history_length=2)
previous_action = 0.0
left_predecessor = dynamic_pair.system.predecessor(
    dynamic_pair.left_state, previous_action
)
right_predecessor = dynamic_pair.system.predecessor(
    dynamic_pair.right_state, previous_action
)
left_history = history_observer.observe(
    (left_predecessor, dynamic_pair.left_state), (previous_action,)
)
right_history = history_observer.observe(
    (right_predecessor, dynamic_pair.right_state), (previous_action,)
)
recovered_velocities = (
    reconstruct_current_velocity(
        previous_position=left_predecessor.position,
        current_position=dynamic_pair.left_state.position,
        previous_action=previous_action,
        time_step=dynamic_pair.system.time_step,
    ),
    reconstruct_current_velocity(
        previous_position=right_predecessor.position,
        current_position=dynamic_pair.right_state.position,
        previous_action=previous_action,
        time_step=dynamic_pair.system.time_step,
    ),
)
history_action_audit = audit_exact_action_fibers(
    [left_history, right_history], dynamic_pair.action_safety_margins
)

partial_observability_summary = {
    "saturated_sensor_static_defect": static_sensor_audit.exact_defect,
    "position_only_static_defect_for_dynamic_pair": dynamic_static_audit.exact_defect,
    "position_only_forced_action_violation": dynamic_action_audit.worst_required_violation,
    "history_observations_separate_pair": left_history != right_history,
    "history_recovered_velocities": recovered_velocities,
    "history_action_conflicts": history_action_audit.conflicting_fiber_count,
}
display(partial_observability_summary)

assert static_sensor_audit.exact_defect == 0.5
assert dynamic_static_audit.exact_defect == 0.0
assert dynamic_action_audit.worst_required_violation == 0.25
assert recovered_velocities == (
    dynamic_pair.left_state.velocity,
    dynamic_pair.right_state.velocity,
)
assert history_action_audit.conflicting_fiber_count == 0
"""
        ),
        _markdown("## 6. Visual audit and machine-checked gate summary"),
        _code(
            r"""
fig, axes = plt.subplots(1, 2, figsize=(10.5, 3.8))
axes[0].step(deltas, near_values, where="post", marker="o", label="original")
axes[0].step(deltas, scaled_values, where="post", linestyle="--", label="codes/radius scaled")
axes[0].axvline(eta, color="black", alpha=0.35, linestyle=":", label=r"planted $\eta$")
axes[0].set(xlabel="pre-registered latent radius", ylabel="maximum witnessed safe margin")
axes[0].set_title("Known near-collision")
axes[0].legend(frameon=False)

axes[1].plot(
    [row["safe_samples"] for row in density_rows],
    [row["1nn_cross_fraction"] for row in density_rows],
    marker="o",
)
axes[1].set(xlabel="safe samples (balanced)", ylabel="cross-boundary 1-NN fraction")
axes[1].set_title("Sampling-dependent diagnostic")
axes[1].set_xscale("log")
fig.tight_layout()
plt.show()

gates = {
    "injective_exact_zero": identity_audit.exact_defect == 0.0,
    "fold_recovers_planted_defect": folded_audit.exact_defect == 1.0,
    "near_collision_transition": near_values[deltas.index(eta)] == 1.0,
    "joint_rescaling_invariant": bool(np.allclose(near_values, scaled_values)),
    "nearest_neighbor_is_sampling_sensitive": (
        len({row["1nn_cross_fraction"] for row in density_rows}) > 1
        and len({row["1nn_cross_fraction"] for row in balance_rows}) > 1
    ),
    "action_conflict_detected": action_audit.conflicting_fiber_count == 1,
    "observation_floor_recovered": (
        static_sensor_audit.exact_defect == 0.5
        and dynamic_action_audit.worst_required_violation == 0.25
    ),
    "history_separates_hidden_velocity": (
        left_history != right_history and history_action_audit.conflicting_fiber_count == 0
    ),
}
assert all(gates.values()), gates
print(json.dumps(gates, indent=2, sort_keys=True))
"""
        ),
        _markdown(
            r"""
## Takeaways and next decision

The implemented measurements pass these deterministic controls. The main practical lesson is that
an exact-code audit and a fixed-radius robust audit answer different questions, while an
unthresholded nearest-neighbor mismatch answers neither one without calibration. The action-fiber
test also catches information loss that the static safe/unsafe label alone cannot see.

**Decision status:** E0 is only partially passed. These controls validate reference semantics, but
do not yet validate continuous collision search, uncertainty-set calibration, sampling coverage,
or confidence statements. No trained-model or ICML claim should cite this notebook as empirical
evidence. The next gate is the controlled dynamical benchmark plus boundary-stratified held-out
evaluation.
"""
        ),
    ]
    return _notebook(cells, experiment="E0 estimator validation")


def _e1_notebook() -> nbf.NotebookNode:
    cells = [
        _markdown(
            r"""
# E1 — GPU-ready visual world-model pilot

**TL;DR.** This notebook validates the complete learned-representation interface on a tiny real
pixel dataset: deterministic trajectory-level splits, hidden-velocity RGB histories, analytic
safety/action labels, AE or beta-VAE construction, latent transition, safety heads, and a finite
forward/backward optimization step. It also materializes the exact 96-task two-domain decision
pilot and shows how to launch one task or a Slurm array. The persisted outputs are engineering evidence only;
one epoch, one batch, or a selected seed is not an ICML result.

The full command-line trainer additionally writes hashed checkpoints, rollout metrics, calibration
and test audit records, and failure-aware manifests. This notebook is generated by
`scripts/build_notebooks.py`.
"""
        ),
        _markdown(
            r"""
## Assumptions and experiment boundary

- The notebook visualizes the controlled cart; a separate controlled-pendulum config exercises the
  same interface. These are two synthetic dynamics, not yet a broad confirmatory benchmark suite.
  A single frame hides velocity; two or four frames can reveal it.
- `h = position_limit - |position|`. The safe-action profile is a declared finite action grid and
  finite nominal horizon, not a continuous-action viability kernel.
- `stack_h1` and `stack_h4` share a fixed-width `(last, last-first)` feature summary and therefore
  the same model parameter count; the latter alone receives nonzero temporal-difference input.
- Checkpoints are selected using validation **world-model utility only**. Test safety labels never
  choose epochs, radii, weights, or architectures.
- The pilot uses three paired seeds and is exploratory. The confirmatory protocol still requires
  eight paired seeds on selected arms after the estimator and prevalence gates pass.
"""
        ),
        _code(
            r"""
from itertools import product
from pathlib import Path
import dataclasses
import json
import os
import shlex
import subprocess
import sys

import matplotlib
import matplotlib.pyplot as plt
import numpy as np
from IPython.display import Markdown, display

ROOT = Path.cwd()
if ROOT.name == "notebooks":
    ROOT = ROOT.parent
elif (ROOT / "LatentSafety" / "src").exists():
    ROOT = ROOT / "LatentSafety"
if not (ROOT / "src" / "latent_safety").exists():
    raise RuntimeError(f"Could not locate repository root from {Path.cwd()}")
sys.path.insert(0, str(ROOT / "src"))

from latent_safety.learning import (
    build_datasets,
    build_world_model,
    cpu_smoke_config,
    dry_run_plan,
    generate_trajectories,
    load_config,
    render_state,
    require_torch,
)
from latent_safety.learning.losses import boundary_contrastive_loss, compute_losses

CONFIG_PATH = ROOT / "configs" / "e1_world_models" / "torch_pilot.toml"
base_config = load_config(CONFIG_PATH)
smoke_config = cpu_smoke_config(base_config)
plan = dry_run_plan(smoke_config)
display(plan)
assert plan["torch_required"] is False
assert set(plan["trajectory_counts"]) == {"train", "validation", "calibration", "test"}
assert all(count > 0 for count in plan["trajectory_counts"].values())
"""
        ),
        _markdown("## 1. Inspect the deterministic visual benchmark before touching the model"),
        _code(
            r"""
trajectories = generate_trajectories(smoke_config.data, seed=smoke_config.run.seed)
split_counts = {
    split: sum(trajectory.split == split for trajectory in trajectories)
    for split in ("train", "validation", "calibration", "test")
}
all_margins = [margin for trajectory in trajectories for margin in trajectory.safety_margins]
unsafe_fraction = sum(margin < 0.0 for margin in all_margins) / len(all_margins)
profile_variation_fraction = np.mean([
    max(profile) - min(profile) > 1e-6
    for trajectory in trajectories
    for profile in trajectory.action_safety_margins
])

data_summary = {
    "trajectories": len(trajectories),
    "split_trajectory_counts": split_counts,
    "frames": len(all_margins),
    "unsafe_frame_fraction": unsafe_fraction,
    "action_profile_variation_fraction": float(profile_variation_fraction),
}
display(data_summary)
assert unsafe_fraction > 0.0, "the smoke fixture must include unsafe examples"
assert profile_variation_fraction > 0.0, "actions must differ in safety somewhere"

trajectory = trajectories[0]
frame_indices = (0, 3, 6, 9)
fig, axes = plt.subplots(1, len(frame_indices), figsize=(10.5, 2.7))
for axis, frame_index in zip(axes, frame_indices, strict=True):
    flat = render_state(trajectory.states[frame_index], smoke_config.data)
    channel_first = np.asarray(flat).reshape(
        smoke_config.data.channels,
        smoke_config.data.image_size,
        smoke_config.data.image_size,
    )
    image = np.moveaxis(channel_first, 0, -1)
    axis.imshow(image, vmin=0.0, vmax=1.0)
    axis.set_title(
        f"t={frame_index}\np={trajectory.states[frame_index].position:+.2f}, "
        f"v={trajectory.states[frame_index].velocity:+.2f}"
    )
    axis.axis("off")
fig.suptitle("Rendered history (velocity is privileged text, not a pixel channel)")
fig.tight_layout()
plt.show()
"""
        ),
        _markdown(
            r"""
## 2. Real PyTorch forward/backward integration check

This imports PyTorch only here, builds all four dataset splits and the configured beta-VAE/GRU
world model, and performs one optimizer step on a real RGB history batch. It checks tensor shapes,
finite objectives, nonzero gradients, and evaluation-latent determinism. It deliberately does not
interpret the one-batch loss as model quality.
"""
        ),
        _code(
            r"""
modules = require_torch()
torch = modules.torch
torch.manual_seed(smoke_config.run.seed)
bundle = build_datasets(
    smoke_config.data,
    seed=smoke_config.run.seed,
    torch=torch,
)
loader = torch.utils.data.DataLoader(
    bundle.datasets["train"],
    batch_size=smoke_config.run.batch_size,
    shuffle=False,
    num_workers=0,
)
batch = next(iter(loader))
model = build_world_model(modules, smoke_config.model, smoke_config.data)
model.train()
optimizer = torch.optim.AdamW(model.parameters(), lr=smoke_config.run.learning_rate)
optimizer.zero_grad(set_to_none=True)
outputs = model(batch["history"], batch["action"])
with torch.no_grad():
    target_latent = model.encode(batch["next_history"], sample=False)["z"]
losses = compute_losses(
    modules,
    outputs,
    target_latent,
    batch,
    smoke_config.objective,
)
assert all(bool(torch.isfinite(value).item()) for value in losses.values())
losses["total"].backward()
gradient_norm = torch.sqrt(sum(
    parameter.grad.detach().square().sum()
    for parameter in model.parameters()
    if parameter.grad is not None
))
assert float(gradient_norm) > 0.0
optimizer.step()

model.eval()
with torch.no_grad():
    first_mean = model.encode(batch["history"], sample=False)["mean"]
    second_mean = model.encode(batch["history"], sample=False)["mean"]
assert torch.equal(first_mean, second_mean)
assert tuple(batch["history"].shape[1:]) == (
    smoke_config.data.history_length,
    smoke_config.data.channels,
    smoke_config.data.image_size,
    smoke_config.data.image_size,
)
assert outputs["predicted_action_profile"].shape[-1] == len(smoke_config.data.actions)

integration_summary = {
    "torch": str(torch.__version__),
    "cuda_available_here": bool(torch.cuda.is_available()),
    "dataset_manifest_sha256": bundle.manifest_sha256,
    "train_samples": len(bundle.datasets["train"]),
    "batch_history_shape": list(batch["history"].shape),
    "latent_shape": list(outputs["mean"].shape),
    "parameter_count": sum(parameter.numel() for parameter in model.parameters()),
    "gradient_norm": float(gradient_norm),
    "losses": {name: float(value.detach()) for name, value in losses.items()},
}
display(integration_summary)

# Capacity audit for the primary memoryless-versus-history comparison.
stack_model_config = dataclasses.replace(smoke_config.model, history_encoder="stack")
stack_counts = {}
for history_length in (1, 4):
    data_config = dataclasses.replace(smoke_config.data, history_length=history_length)
    comparison_model = build_world_model(modules, stack_model_config, data_config)
    stack_counts[f"stack_h{history_length}"] = sum(
        parameter.numel() for parameter in comparison_model.parameters()
    )
assert stack_counts["stack_h1"] == stack_counts["stack_h4"]
display({"capacity_matched_stack_parameter_counts": stack_counts})

probe_latent = torch.tensor(
    [[1.0, 0.2], [-0.4, 1.0], [0.7, -0.8], [-0.9, -0.3]],
    dtype=torch.float32,
)
probe_margin = torch.tensor([0.10, -0.10, 0.03, -0.03], dtype=torch.float32)
base_boundary_loss = boundary_contrastive_loss(
    modules, probe_latent, probe_margin, smoke_config.objective
)
rescaled_boundary_loss = boundary_contrastive_loss(
    modules, 1000.0 * probe_latent, probe_margin, smoke_config.objective
)
assert torch.allclose(base_boundary_loss, rescaled_boundary_loss, atol=1e-7, rtol=1e-7)
display({
    "unit_normalized_boundary_loss": float(base_boundary_loss),
    "loss_after_1000x_code_rescaling": float(rescaled_boundary_loss),
})
"""
        ),
        _markdown(
            r"""
## 3. Optional end-to-end smoke with manifests

The command below trains one epoch and evaluates every split. It is skipped by default because it
writes an ignored run directory. To run it during notebook execution, set
`LATENT_SAFETY_NOTEBOOK_E2E=1` and optionally `LATENT_SAFETY_NOTEBOOK_OUTPUT` to a new, empty path.
The trainer refuses to overwrite a nonempty run directory.
"""
        ),
        _code(
            r"""
run_e2e = os.environ.get("LATENT_SAFETY_NOTEBOOK_E2E") == "1"
e2e_output = Path(os.environ.get(
    "LATENT_SAFETY_NOTEBOOK_OUTPUT",
    "runs/e1_world_models/notebook_cpu_smoke",
))
e2e_command = [
    sys.executable,
    str(ROOT / "scripts" / "run_e1_torch.py"),
    "--config",
    str(CONFIG_PATH),
    "--smoke",
    "--output",
    str(e2e_output),
]
if run_e2e:
    subprocess.run(e2e_command, cwd=ROOT, check=True)
else:
    print("Skipped write-producing E2E run. Command:")
    print(shlex.join(e2e_command))
"""
        ),
        _markdown(
            r"""
## 4. Pre-registered paired decision pilot

The first GPU gate is exactly `2 domains × 2 model families × 2 capacity-matched history modes ×
1 latent dimension × 4 safety arms × 3 paired seeds = 96` tasks. `stack_h1` is the true memoryless
control and `stack_h4` adds four-frame information without changing the fixed-width stack model's
parameter count. Every task records its domain, history mode, encoder, and length and has a unique
output directory. The three-seed grid is exploratory; only validation utility and a predeclared
Pareto rule may authorize an eight-seed confirmatory stage.

The checked-in 288-task full expansion adds `gru_h4` and latent dimension 4 only after the decisive
pilot passes. Each domain is analyzed first on its own; domain is not treated as another seed.
"""
        ),
        _code(
            r"""
families = ("ae", "beta_vae")
history_modes = {
    "stack_h1": ("stack", 1),
    "stack_h4": ("stack", 4),
}
latent_dimensions = (8,)
safety_arms = ("none", "h_prediction", "boundary_contrastive", "safe_action_profile")
seeds = (0, 1, 2)
domains = {
    "cart": "configs/e1_world_models/torch_pilot.toml",
    "pendulum": "configs/e1_world_models/torch_pendulum_pilot.toml",
}
pilot_commands = []
for domain, family, history_mode, dimension, arm, seed in product(
    domains, families, history_modes, latent_dimensions, safety_arms, seeds
):
    history_encoder, history_length = history_modes[history_mode]
    output = (
        ROOT / "runs" / "e1_world_models" / f"decisive_{domain}_grid"
        / f"{family}_{history_mode}_d{dimension}" / arm / f"seed_{seed}"
    )
    command = [
        "python",
        "scripts/run_e1_torch.py",
        "--config", domains[domain],
        "--output", str(output),
        "--device", "cuda",
        "--seed", str(seed),
        "--model-family", family,
        "--history-encoder", history_encoder,
        "--history-length", str(history_length),
        "--latent-dim", str(dimension),
        "--safety-arm", arm,
    ]
    pilot_commands.append(command)

assert len(pilot_commands) == 96
assert len({command[command.index("--output") + 1] for command in pilot_commands}) == 96
display({
    "task_count": len(pilot_commands),
    "domains": domains,
    "history_modes": history_modes,
    "paired_seeds": list(seeds),
    "first_four_commands": [shlex.join(command) for command in pilot_commands[:4]],
})
"""
        ),
        _markdown(
            r"""
## 5. High-GPU launch and post-training audit

From the repository root, generate the immutable task plan and submit the array:

```bash
python scripts/plan_e1_sweep.py \
  --grid configs/e1_world_models/decisive_cart_grid.toml \
  --output runs/plans/e1_decisive_cart.json
python scripts/plan_e1_sweep.py \
  --grid configs/e1_world_models/decisive_pendulum_grid.toml \
  --output runs/plans/e1_decisive_pendulum.json
mkdir -p runs/slurm
sbatch experiments/e1_world_models/slurm_decisive_cart_array.sh
sbatch experiments/e1_world_models/slurm_decisive_pendulum_array.sh
```

For a workstation, run one indexed task without shell-generated commands:

```bash
python scripts/run_e1_sweep_task.py \
  --plan runs/plans/e1_decisive_cart.json --index 0 --device cuda
```

Then audit the frozen test codes at radii scaled using **calibration codes only**:

```bash
python scripts/audit_e1_records.py \
  --config configs/e1_world_models/torch_pilot.toml \
  --calibration runs/.../audit_calibration.jsonl \
  --test runs/.../audit_test.jsonl \
  --output runs/.../latent_safety_audit.json \
  --relative-radii 0 0.01 0.02 0.05 0.10
```

These relative radii are a scale-equivariant diagnostic convention, not a deployment
certificate. A paper guarantee needs a physical uncertainty set or verified set propagation.
"""
        ),
        _markdown(
            r"""
## Takeaways and next decision

The visual data/model interface passes a genuine in-memory PyTorch gradient-step check, and the
96-task two-domain decision pilot is fully specified with unique outputs and paired seeds. The command-line path can
also run one CPU epoch end to end and emit provenance-complete artifacts.

**Readiness:** engineering-ready for a small GPU pilot, not evidence-ready for the manuscript. The
next scientific decision is whether ordinary and safety-aware encoders separate on the calibrated
static/action curves at matched validation world-model utility. If the effect vanishes under
history encoders, trajectory splits, or observation-level controls, the project should pivot to a
narrower dynamic-theory or control-venue contribution rather than scale the grid.
"""
        ),
    ]
    return _notebook(
        cells,
        experiment="E1 controlled-cart visual world-model pilot",
        status="engineering_smoke_not_paper_evidence",
    )


def _analysis_notebook() -> nbf.NotebookNode:
    cells = [
        _markdown(
            r"""
# E1/E2 analysis template — paired seeds, validation frontier, and multiplicity

**TL;DR.** This notebook encodes the analysis contract before GPU results exist. The authoritative
`aggregate_e1_sweep.py` command verifies the complete plan, run/audit provenance, and paired seed
cells before it builds a validation-only safety/utility frontier. This notebook consumes only those
fail-closed aggregate artifacts; it never reconstructs a result from an opportunistic subset of run
directories and keeps final-test labels out of selection. The persisted numerical example is
explicitly synthetic and exists only to regression-test the statistics code. It is not evidence for
the method.

Once either 48-task domain component is complete, run the aggregator documented in the E1 handoff and
then rerun this notebook. Incomplete aggregates remain visible as a ledger but cannot become a real
result panel.
"""
        ),
        _markdown(
            r"""
## Assumptions and analysis contract

- Pair by the same training seed within task/model/history/dimension; never pool video frames as
  independent replicates.
- Minimize both validation world-model utility loss and the prospectively frozen validation safety
  defect. Report reconstruction and maximum-predeclared-horizon rollout pixel MSE separately; the
  family-dependent composite is not a global AE-versus-beta-VAE matching scale.
- Use the radius and safety budget frozen in `configs/e1_world_models/decisive_cart_grid.toml`.
- Three seeds are exploratory. Confirmatory intervals require the selected eight-seed design (or a
  preregistered precision argument) and are reported with all failures/timeouts.
- Holm correction requires a predeclared hypothesis family and valid raw p-values; it cannot repair
  selective analysis.
"""
        ),
        _code(
            r"""
from dataclasses import asdict
from pathlib import Path
import json
import sys
import tomllib

import matplotlib.pyplot as plt
import numpy as np
from IPython.display import Markdown, display

ROOT = Path.cwd()
if ROOT.name == "notebooks":
    ROOT = ROOT.parent
elif (ROOT / "LatentSafety" / "src").exists():
    ROOT = ROOT / "LatentSafety"
if not (ROOT / "src" / "latent_safety").exists():
    raise RuntimeError(f"Could not locate repository root from {Path.cwd()}")
sys.path.insert(0, str(ROOT / "src"))

from latent_safety.analysis import (
    BLOCK_INDEPENDENCE_CAVEAT,
    VALIDATION_SELECTION_CAVEAT,
    HypothesisPValue,
    PairedBlock,
    ValidationScore,
    exact_paired_sign_flip_test,
    holm_adjust,
    paired_block_bootstrap_ci,
    select_under_safety_budget,
    standardized_paired_effect,
    validation_pareto_frontier,
)

GRID_PATH = ROOT / "configs" / "e1_world_models" / "decisive_cart_grid.toml"
with GRID_PATH.open("rb") as stream:
    grid_config = tomllib.load(stream)
analysis_config = grid_config["analysis"]
display({
    "block_caveat": BLOCK_INDEPENDENCE_CAVEAT,
    "selection_caveat": VALIDATION_SELECTION_CAVEAT,
    "frozen_analysis_config": analysis_config,
})
"""
        ),
        _markdown("## 1. Fail-closed aggregate audit"),
        _code(
            r"""
aggregate_paths = {
    "cart": ROOT / "runs" / "analysis" / "e1_pilot_validation.json",
    "pendulum": ROOT / "runs" / "analysis" / "e1_pendulum_pilot_validation.json",
}
aggregate_reports = {}
aggregate_status = {}
for domain, path in aggregate_paths.items():
    if not path.is_file():
        aggregate_status[domain] = {
            "artifact": str(path),
            "status": "missing",
            "analysis_ready": False,
        }
        continue
    report = json.loads(path.read_text(encoding="utf-8"))
    if report.get("schema_version") != 1:
        raise RuntimeError(f"Unsupported aggregate schema for {domain}: {path}")
    if report.get("selection_uses_test_data") is not False:
        raise RuntimeError(f"Aggregate does not preserve validation-only selection: {path}")
    completeness = report.get("completeness", {})
    aggregate_status[domain] = {
        "artifact": str(path),
        "status": report.get("status"),
        "analysis_ready": bool(report.get("analysis_ready")),
        "planned_tasks": completeness.get("planned_task_count"),
        "successful_tasks": completeness.get("successful_task_count"),
        "missing_tasks": completeness.get("missing_task_count"),
        "failed_tasks": completeness.get("failed_task_count"),
        "test_unblinded": report.get("test_unblinded"),
    }
    if report.get("status") == "complete" and report.get("analysis_ready") is True:
        aggregate_reports[domain] = report

display(aggregate_status)
"""
        ),
        _markdown(
            r"""
## 2. Synthetic regression fixture for paired inference

The values below are fabricated and labelled as such. They verify difference direction, seed
pairing, deterministic bootstrap output, and zero-variance handling. Smaller defect is better, so a
negative `candidate - baseline` estimate favors the candidate.
"""
        ),
        _code(
            r"""
synthetic_baseline = (0.42, 0.39, 0.46, 0.41, 0.44, 0.38, 0.45, 0.43)
synthetic_candidate = (0.31, 0.35, 0.34, 0.36, 0.33, 0.32, 0.37, 0.34)
synthetic_blocks = tuple(
    PairedBlock(f"synthetic-seed-{seed}", baseline, candidate)
    for seed, (baseline, candidate) in enumerate(
        zip(synthetic_baseline, synthetic_candidate, strict=True)
    )
)
synthetic_ci = paired_block_bootstrap_ci(
    synthetic_blocks,
    resamples=int(analysis_config["bootstrap_resamples"]),
    seed=int(analysis_config["bootstrap_seed"]),
)
synthetic_effect = standardized_paired_effect(synthetic_blocks)
synthetic_randomization = exact_paired_sign_flip_test(
    synthetic_blocks,
    alternative="candidate_less",
    exchangeability_justification=(
        "synthetic paired method labels are exchangeable under the constructed sharp null"
    ),
)
display({
    "status": "SYNTHETIC CODE REGRESSION — NOT A RESULT",
    "paired_ci": asdict(synthetic_ci),
    "paired_effect": asdict(synthetic_effect),
    "exact_sign_flip": asdict(synthetic_randomization),
})
assert synthetic_ci.n_blocks == 8
assert synthetic_ci.estimate < 0.0
assert synthetic_effect.is_defined
assert synthetic_randomization.permutation_count == 2 ** len(synthetic_blocks)
assert synthetic_randomization.p_value == 1.0 / synthetic_randomization.permutation_count
"""
        ),
        _markdown("## 3. Validation-only Pareto selection regression"),
        _code(
            r"""
synthetic_validation_scores = (
    ValidationScore("baseline", safety_defect=0.42, utility_loss=0.20),
    ValidationScore("h_prediction", safety_defect=0.31, utility_loss=0.22),
    ValidationScore("boundary", safety_defect=0.22, utility_loss=0.25),
    ValidationScore("action_profile", safety_defect=0.18, utility_loss=0.29),
    ValidationScore("dominated_control", safety_defect=0.45, utility_loss=0.30),
)
synthetic_frontier = validation_pareto_frontier(synthetic_validation_scores)
synthetic_selection = select_under_safety_budget(
    synthetic_frontier,
    max_safety_defect=0.25,
)
display({
    "status": "SYNTHETIC CODE REGRESSION — NOT A RESULT",
    "frontier": [asdict(point) for point in synthetic_frontier.points],
    "dominated": synthetic_frontier.dominated_config_ids,
    "selected_under_synthetic_budget_0.25": asdict(synthetic_selection),
})
assert "dominated_control" in synthetic_frontier.dominated_config_ids
assert synthetic_selection.config_id == "boundary"
"""
        ),
        _markdown("## 4. Multiplicity-control regression"),
        _code(
            r"""
synthetic_holm = holm_adjust(
    (
        HypothesisPValue("synthetic_H_static", 0.008),
        HypothesisPValue("synthetic_H_action", 0.021),
        HypothesisPValue("synthetic_H_downstream", 0.11),
    ),
    alpha=0.05,
)
display({
    "status": "SYNTHETIC CODE REGRESSION — NOT A RESULT",
    "holm": [asdict(item) for item in synthetic_holm],
})
assert [item.rejected for item in synthetic_holm] == [True, True, False]
"""
        ),
        _markdown("## 5. Visual regression checks"),
        _code(
            r"""
fig, axes = plt.subplots(1, 2, figsize=(10.5, 3.8))
seed_indices = np.arange(len(synthetic_baseline))
for seed, baseline, candidate in zip(
    seed_indices, synthetic_baseline, synthetic_candidate, strict=True
):
    axes[0].plot([0, 1], [baseline, candidate], marker="o", alpha=0.75)
axes[0].set_xticks([0, 1], ["baseline", "candidate"])
axes[0].set_ylabel("synthetic defect (smaller is better)")
axes[0].set_title("Paired seed-level values")

for point in synthetic_validation_scores:
    on_frontier = point in synthetic_frontier.points
    axes[1].scatter(
        point.utility_loss,
        point.safety_defect,
        marker="o" if on_frontier else "x",
        s=55,
    )
    axes[1].annotate(point.config_id, (point.utility_loss, point.safety_defect), fontsize=7)
axes[1].set(xlabel="validation utility loss", ylabel="validation safety defect")
axes[1].set_title("Synthetic validation frontier")
fig.tight_layout()
plt.show()
"""
        ),
        _markdown(
            r"""
## 6. Real pilot aggregate display (only complete, provenance-checked artifacts)

Frontier construction and paired inference happen in the fail-closed aggregator, which validates
the declared plan hash, factorial coverage, checkpoint provenance, audit radii, and complete seed
cells. This cell displays only reports whose status is `complete` and `analysis_ready`; a partial or
rejected report cannot enter. The final test table belongs in a separate, locked unblinding step
after the rule and included seeds are frozen.
"""
        ),
        _code(
            r"""
if aggregate_reports:
    for domain, report in sorted(aggregate_reports.items()):
        frontier = report["validation_frontier"]
        utility_component_rows = [
            {
                "config_id": row["config_id"],
                "model_family": row["model_family"],
                "history_mode": row["history_mode"],
                "safety_arm": row["safety_arm"],
                "median_selection_composite": row["validation_median"]["utility_loss"],
                "median_reconstruction_mse": row["validation_median"]["reconstruction_mse"],
                "median_rollout_pixel_mse": row["validation_median"][
                    "rollout_pixel_mse_at_max_horizon"
                ],
                "rollout_horizon": row["rollout_summary_horizon"],
            }
            for row in report["model_rows"]
        ]
        display({
            "status": "REAL COMPLETE VALIDATION-ONLY PILOT AGGREGATE",
            "domain": domain,
            "source_plan_sha256": report["source_plan"]["plan_sha256"],
            "successful_tasks": report["completeness"]["successful_task_count"],
            "complete_seed_model_cells": len(report["model_rows"]),
            "frontier": frontier["points"],
            "predeclared_selection_status": frontier["budget_selection_status"],
            "predeclared_selection": frontier["selected"],
            "utility_component_rows": utility_component_rows,
            "paired_comparison_count": len(report["paired_seed_comparisons"]),
            "test_access": report["analysis_contract"]["test_access"],
        })
else:
    display(Markdown(
        "**No complete, analysis-ready GPU pilot aggregates found.** This is the expected "
        "repository state before the sweeps; only the explicitly synthetic regression outputs "
        "above are active. Run `scripts/aggregate_e1_sweep.py` after every planned task has "
        "finished."
    ))
"""
        ),
        _markdown(
            r"""
## Takeaways and unblinding gate

The inferential machinery is executable before results arrive: paired seed/block bootstrap,
explicit standardized-effect edge cases, Holm step-down correction, and validation-only Pareto
selection. The notebook refuses to invent a real aggregate when run/audit artifacts are missing.

Before any confirmatory test unblinding, freeze: included configuration IDs and failed runs; the
primary radius; safety budget; effect direction; resampling unit; hypothesis family; and exact
producing commit/environment. The current trainer's three-seed pilot evaluates test for engineering
convenience, so it is exploratory. A final study should use a deferred-test execution path or an
independent custodian to preserve a genuine blind.
"""
        ),
    ]
    return _notebook(
        cells,
        experiment="E1/E2 paired analysis and validation selection",
        status="analysis_template_synthetic_regression_not_paper_evidence",
    )


def _two_domain_oracle_notebook() -> nbf.NotebookNode:
    cells = [
        _markdown(
            r"""
# Two-domain partial-observability controls

**TL;DR.** In both controlled pixel domains, two states can render exactly the same current frame
while hidden velocity changes the finite-horizon safe-action set. The single-frame observation
fiber is action-conflicted: every state has a safe audited action, but no action is safe for both.
A four-frame visible-position/direction history separates the constructed histories, and the
privileged state oracle separates them immediately. These are exact synthetic controls for
attribution, not learned-model results or long-horizon certificates.
"""
        ),
        _markdown(
            r"""
## Assumptions and scope

- The cart and pendulum are repository-defined deterministic synthetic fixtures, not Gym tasks.
- Pixels expose position or angle plus nuisance but never velocity; the compared states share the
  same nuisance phase, so their current images are byte-for-byte equal.
- Safe-action margins use the frozen three-action grid and constant-action nominal rollout horizon
  from each config. They are not continuous-action viability kernels.
- `observation_feature_vector` is an evaluation oracle for visible kinematic factors, not a learned
  pixel encoder. `state_feature_vector` is privileged and nondeployable.
"""
        ),
        _code(
            r"""
import dataclasses
from pathlib import Path
import sys

import matplotlib.pyplot as plt
import numpy as np
from IPython.display import display

ROOT = Path.cwd()
if ROOT.name == "notebooks":
    ROOT = ROOT.parent
elif (ROOT / "LatentSafety" / "src").exists():
    ROOT = ROOT / "LatentSafety"
if not (ROOT / "src" / "latent_safety").exists():
    raise RuntimeError(f"Could not locate repository root from {Path.cwd()}")
sys.path.insert(0, str(ROOT / "src"))

from latent_safety.learning import (
    CartState,
    PendulumState,
    action_safety_profile,
    load_config,
    observation_feature_vector,
    render_state,
    state_feature_vector,
)
from latent_safety.metrics.action import audit_exact_action_fibers

cart_config = load_config(
    ROOT / "configs" / "e1_world_models" / "torch_pilot.toml"
).data
pendulum_config = load_config(
    ROOT / "configs" / "e1_world_models" / "torch_pendulum_pilot.toml"
).data
display({
    "cart_task": cart_config.task,
    "pendulum_task": pendulum_config.task,
    "action_grid_cart": cart_config.actions,
    "action_grid_pendulum": pendulum_config.actions,
})
"""
        ),
        _markdown("## 1. Exact single-frame aliases with conflicting actions"),
        _code(
            r"""
fixtures = {
    "cart": {
        "config": cart_config,
        "states": (
            CartState(position=-0.25, velocity=-1.75, nuisance_phase=0.2),
            CartState(position=-0.25, velocity=2.45, nuisance_phase=0.2),
        ),
    },
    "pendulum": {
        "config": pendulum_config,
        "states": (
            PendulumState(angle=-0.60, angular_velocity=-0.50, nuisance_phase=0.2),
            PendulumState(angle=-0.60, angular_velocity=2.50, nuisance_phase=0.2),
        ),
    },
}

alias_rows = []
for task, fixture in fixtures.items():
    config = fixture["config"]
    left, right = fixture["states"]
    left_pixels = render_state(left, config)
    right_pixels = render_state(right, config)
    profiles = (action_safety_profile(left, config), action_safety_profile(right, config))
    h1_config = dataclasses.replace(config, history_length=1)
    h1_codes = (
        observation_feature_vector((left,), 0, h1_config),
        observation_feature_vector((right,), 0, h1_config),
    )
    action_audit = audit_exact_action_fibers(h1_codes, profiles)
    safe_sets = [
        tuple(action for action, margin in zip(config.actions, profile, strict=True) if margin >= 0)
        for profile in profiles
    ]
    assert left_pixels == right_pixels
    assert h1_codes[0] == h1_codes[1]
    assert all(safe_sets)
    assert not set(safe_sets[0]).intersection(safe_sets[1])
    assert action_audit.conflicting_fiber_count == 1
    assert state_feature_vector(left, config) != state_feature_vector(right, config)
    alias_rows.append({
        "task": task,
        "pixels_exactly_equal": left_pixels == right_pixels,
        "h1_observation_code": h1_codes[0],
        "safe_actions_state_0": safe_sets[0],
        "safe_actions_state_1": safe_sets[1],
        "required_common_action_violation": action_audit.worst_required_violation,
        "privileged_states_distinct": True,
    })

display(alias_rows)
"""
        ),
        _markdown(
            r"""
## 2. Four-frame visible histories remove the constructed alias

The histories end at the same visible position/direction but arrive from opposite directions. H1
therefore sees equal codes; H4 sees different ordered visible-factor sequences. Distinct H4 fibers
permit different actions, so the exact finite audit no longer reports an alias-induced conflict.
"""
        ),
        _code(
            r"""
cart_paths = (
    tuple(CartState(position, -1.75, 0.1 * index) for index, position in enumerate((-0.10, -0.15, -0.20, -0.25))),
    tuple(CartState(position, 2.45, 1.0 + 0.1 * index) for index, position in enumerate((-0.40, -0.35, -0.30, -0.25))),
)
pendulum_paths = (
    tuple(PendulumState(angle, -0.50, 0.1 * index) for index, angle in enumerate((-0.30, -0.40, -0.50, -0.60))),
    tuple(PendulumState(angle, 2.50, 1.0 + 0.1 * index) for index, angle in enumerate((-0.90, -0.80, -0.70, -0.60))),
)

history_rows = []
for task, paths, config in (
    ("cart", cart_paths, cart_config),
    ("pendulum", pendulum_paths, pendulum_config),
):
    h1 = dataclasses.replace(config, history_length=1)
    h4 = dataclasses.replace(config, history_length=4)
    h1_codes = tuple(observation_feature_vector(path, 3, h1) for path in paths)
    h4_codes = tuple(observation_feature_vector(path, 3, h4) for path in paths)
    profiles = tuple(action_safety_profile(path[-1], config) for path in paths)
    h1_audit = audit_exact_action_fibers(h1_codes, profiles)
    h4_audit = audit_exact_action_fibers(h4_codes, profiles)
    assert h1_codes[0] == h1_codes[1]
    assert h4_codes[0] != h4_codes[1]
    assert h1_audit.conflicting_fiber_count == 1
    assert h4_audit.conflicting_fiber_count == 0
    history_rows.append({
        "task": task,
        "h1_codes_equal": True,
        "h4_codes_equal": False,
        "h1_action_conflicts": h1_audit.conflicting_fiber_count,
        "h4_action_conflicts": h4_audit.conflicting_fiber_count,
        "h4_observation_dimension": len(h4_codes[0]),
    })

display(history_rows)
"""
        ),
        _markdown("## 3. Pixel-level visual audit"),
        _code(
            r"""
fig, axes = plt.subplots(2, 2, figsize=(7.5, 6.0))
for row, (task, fixture) in enumerate(fixtures.items()):
    config = fixture["config"]
    for column, state in enumerate(fixture["states"]):
        pixels = np.asarray(render_state(state, config)).reshape(
            config.channels, config.image_size, config.image_size
        )
        axes[row, column].imshow(np.moveaxis(pixels, 0, -1), vmin=0.0, vmax=1.0)
        hidden_velocity = state.velocity if task == "cart" else state.angular_velocity
        axes[row, column].set_title(f"{task}, hidden velocity={hidden_velocity:+.2f}")
        axes[row, column].axis("off")
fig.suptitle("Each row is an exact current-frame alias")
fig.tight_layout()
plt.show()

for task, fixture in fixtures.items():
    config = fixture["config"]
    left, right = fixture["states"]
    assert render_state(left, config) == render_state(right, config)
"""
        ),
        _markdown(
            r"""
## Takeaways

Both domains contain an exact, individually viable action conflict before learned compression. A
memoryless encoder cannot repair it because identical input pixels must receive the same
deterministic code. The visible H4 oracle separates the constructed histories, showing precisely
what extra information a history encoder may exploit; the state oracle is a full-information
control.

The result is a benchmark invariant, not evidence that a trained H4 model learns the distinction.
That claim still requires the paired GPU grids, observation-versus-encoder audits, matched utility,
and frozen validation/test analysis. It also remains relative to a finite constant-action profile,
not persistent closed-loop safety.
"""
        ),
    ]
    return _notebook(
        cells,
        experiment="Two-domain observation and state oracle controls",
        status="executed_synthetic_control_not_paper_evidence",
    )


def _theory_notebook() -> nbf.NotebookNode:
    cells = [
        _markdown(
            r"""
# Theory laboratory — exhaustive checks and counterexamples

**TL;DR.** Exhaustive finite enumeration supports two exact statements: a sound certificate is
`m`-complete exactly when no required code also contains an unsafe state, and deterministic
post-processing cannot reduce the exact static defect. The experiments also expose three limits:
the scalar defect alone does not resolve a zero-valued endpoint, randomization only evades an
action-conflict result after weakening pointwise safety to an expectation, and vanishing average
reconstruction error can coexist with fixed worst-case safety ambiguity.

This notebook is a proof-debugging companion. Enumeration can falsify a theorem but cannot prove
its infinite-space version; the manuscript proof must carry its own endpoint, regularity, and
measurability assumptions.
"""
        ),
        _markdown(
            r"""
## Scope and assumptions

- The audited state space, code alphabet, and finite action set are fully enumerated.
- Safe means `h >= 0`; unsafe means `h < 0`; `m`-complete means every state with `h >= m` is
  accepted.
- A certificate is an arbitrary subset of latent codes. Neural/continuous certificate classes may
  have additional approximation or regularity gaps.
- Randomized policies are separated into almost-sure pointwise safety and expected-margin safety;
  these are not interchangeable.
"""
        ),
        _code(
            r"""
from itertools import product
from pathlib import Path
import json
import sys

import matplotlib
import matplotlib.pyplot as plt
import numpy as np
from IPython.display import Markdown, display

ROOT = Path.cwd()
if ROOT.name == "notebooks":
    ROOT = ROOT.parent
elif (ROOT / "LatentSafety" / "src").exists():
    ROOT = ROOT / "LatentSafety"
if not (ROOT / "src" / "latent_safety").exists():
    raise RuntimeError(f"Could not locate repository root from {Path.cwd()}")
sys.path.insert(0, str(ROOT / "src"))

from latent_safety.metrics.action import audit_exact_action_fibers
from latent_safety.metrics.finite import (
    audit_finite_static_fibers,
    check_finite_data_processing,
    check_sound_completeness,
    enumerate_binary_certificates,
)
from latent_safety.synthetic import (
    localized_collision_encoder,
    localized_collision_mse_bound,
    signed_action_margins,
)

print({
    "python": sys.version.split()[0],
    "numpy": np.__version__,
    "matplotlib": matplotlib.__version__,
    "repo_root": str(ROOT),
})
"""
        ),
        _markdown("## 1. Exhaustive static soundness/completeness equivalence"),
        _code(
            r"""
def brute_certificate_exists(latents, margins, completeness_margin):
    codes = tuple(tuple(float(value) for value in latent) for latent in latents)
    for accepted in enumerate_binary_certificates(codes):
        sound = all(
            margin >= 0.0
            for code, margin in zip(codes, margins, strict=True)
            if code in accepted
        )
        complete = all(
            code in accepted
            for code, margin in zip(codes, margins, strict=True)
            if margin >= completeness_margin
        )
        if sound and complete:
            return True
    return False


margins = (-0.4, 0.0, 0.25, 0.9)
margin_grid = (-0.5, -0.1, 0.0, 0.1, 0.25, 0.250001, 0.9, 0.900001)
frontier_cases = 0
for assignment in product(range(3), repeat=len(margins)):
    latents = [(float(code),) for code in assignment]
    for threshold in margin_grid:
        oracle = check_sound_completeness(
            latents, margins, completeness_margin=threshold
        ).exists
        brute = brute_certificate_exists(latents, margins, threshold)
        assert oracle == brute, (assignment, threshold, oracle, brute)
        frontier_cases += 1

print(f"Checked {frontier_cases:,} representation/threshold cases with no discrepancy.")
"""
        ),
        _markdown(
            r"""
## 2. Exhaustive finite data-processing check

For every map from four states into three fine-code labels, we enumerate every binary
post-processing map on those labels. The coarse representation is therefore explicitly `T ∘ R`.
"""
        ),
        _code(
            r"""
data_processing_cases = 0
strict_increases = 0
for fine_assignment in product(range(3), repeat=len(margins)):
    fine = [(float(code),) for code in fine_assignment]
    for post_map_values in product(range(2), repeat=3):
        coarse = [(float(post_map_values[code]),) for code in fine_assignment]
        result = check_finite_data_processing(fine, coarse, margins)
        assert result.is_deterministic_postprocessing
        assert result.monotone
        if result.coarse_defect > result.fine_defect:
            strict_increases += 1
        data_processing_cases += 1

print({
    "coarsenings_checked": data_processing_cases,
    "strict_defect_increases": strict_increases,
    "violations": 0,
})
"""
        ),
        _markdown(
            r"""
## 3. Endpoint diagnostic: the number `epsilon = 0` is not enough

Both examples below have scalar defect zero because the definition adjoins `{0}`. In the first,
the boundary state has a pure safe code; in the second, it shares a code with an unsafe state.
Therefore exact `m=0` completeness is possible in one and impossible in the other. A population
theorem should state strict inequalities unless it separately records attainment/collision at the
endpoint.
"""
        ),
        _code(
            r"""
endpoint_examples = []
for name, latents in {
    "no boundary collision": [(0.0,), (1.0,)],
    "boundary collision": [(0.0,), (0.0,)],
}.items():
    example_margins = (0.0, -0.1)
    audit = audit_finite_static_fibers(latents, example_margins)
    check = check_sound_completeness(
        latents, example_margins, completeness_margin=0.0
    )
    endpoint_examples.append({
        "case": name,
        "scalar_defect": audit.exact_defect,
        "zero_complete_certificate_exists": check.exists,
    })

display(endpoint_examples)
assert endpoint_examples[0]["scalar_defect"] == endpoint_examples[1]["scalar_defect"] == 0.0
assert endpoint_examples[0]["zero_complete_certificate_exists"]
assert not endpoint_examples[1]["zero_complete_certificate_exists"]
"""
        ),
        _markdown(
            r"""
## 4. Deterministic versus randomized action safety

Two states share one code. Their safe action supports are disjoint. No deterministic latent policy
can be pointwise safe, and no randomized policy can be almost-surely safe because its support would
need to lie in the empty intersection. A 50/50 mixture does satisfy a *different*, weaker condition:
nonnegative expected margin for each state. This is exactly why the policy class and safety
semantics must appear in the theorem statement.
"""
        ),
        _code(
            r"""
action_margins = np.asarray([[1.0, -1.0], [-1.0, 1.0]])
action_audit = audit_exact_action_fibers(
    [(0.0,), (0.0,)], action_margins.tolist()
)
q_action_zero = np.linspace(0.0, 1.0, 201)
expected_by_state = np.stack([
    q_action_zero * action_margins[state, 0]
    + (1.0 - q_action_zero) * action_margins[state, 1]
    for state in range(2)
])
worst_expected_margin = expected_by_state.min(axis=0)
best_index = int(np.argmax(worst_expected_margin))

randomized_summary = {
    "deterministic_conflicts": action_audit.conflicting_fiber_count,
    "best_mixture_probability_action_0": float(q_action_zero[best_index]),
    "best_worst_state_expected_margin": float(worst_expected_margin[best_index]),
    "common_almost_sure_safe_action_count": 0,
}
display(randomized_summary)
assert action_audit.conflicting_fiber_count == 1
assert np.isclose(worst_expected_margin[best_index], 0.0)
"""
        ),
        _markdown(
            r"""
### 4b. Pointwise expected-loss slack versus strong fiber-wise slack

The manuscript now keeps these semantics separate. For a finite loss matrix, `beta_exp` minimizes
the worst-state *expected* loss, whereas `beta_strong` averages each action's worst-fiber loss. The
latter is linear over the simplex and therefore equals deterministic slack. We solve both primal
and dual linear programs below and test the finite-action sandwich on random nonnegative matrices.
"""
        ),
        _code(
            r"""
from scipy.optimize import linprog


def finite_action_slacks(loss_matrix):
    loss = np.asarray(loss_matrix, dtype=float)
    state_count, action_count = loss.shape
    deterministic = float(np.min(np.max(loss, axis=0)))

    # Primal: min t, Lp <= t1, p in simplex.
    primal = linprog(
        c=np.r_[np.zeros(action_count), 1.0],
        A_ub=np.c_[loss, -np.ones(state_count)],
        b_ub=np.zeros(state_count),
        A_eq=np.asarray([np.r_[np.ones(action_count), 0.0]]),
        b_eq=np.asarray([1.0]),
        bounds=[(0.0, None)] * action_count + [(None, None)],
        method="highs",
    )
    # Dual: max r, L^T q >= r1, q in simplex.
    dual = linprog(
        c=np.r_[np.zeros(state_count), -1.0],
        A_ub=np.c_[-loss.T, np.ones(action_count)],
        b_ub=np.zeros(action_count),
        A_eq=np.asarray([np.r_[np.ones(state_count), 0.0]]),
        b_eq=np.asarray([1.0]),
        bounds=[(0.0, None)] * state_count + [(None, None)],
        method="highs",
    )
    assert primal.success and dual.success
    pointwise_expected = float(primal.fun)
    dual_value = float(-dual.fun)
    strong = float(np.min(np.max(loss, axis=0)))
    return deterministic, pointwise_expected, strong, dual_value


hard_conflict = np.asarray([[0.0, 1.0], [1.0, 0.0]])
hard_slacks = finite_action_slacks(hard_conflict)
assert np.allclose(hard_slacks, (1.0, 0.5, 1.0, 0.5))

rng = np.random.default_rng(20260821)
finite_action_trials = 100
for _ in range(finite_action_trials):
    loss = rng.uniform(0.0, 2.0, size=(4, 3))
    deterministic, pointwise_expected, strong, dual_value = finite_action_slacks(loss)
    assert deterministic / loss.shape[1] <= pointwise_expected + 1e-9
    assert pointwise_expected <= deterministic + 1e-9
    assert np.isclose(strong, deterministic)
    assert np.isclose(pointwise_expected, dual_value, atol=1e-8)

display({
    "hard_conflict": {
        "deterministic": hard_slacks[0],
        "pointwise_expected": hard_slacks[1],
        "strong_fiber_wise": hard_slacks[2],
        "dual_witness_value": hard_slacks[3],
    },
    "random_nonnegative_matrices_checked": finite_action_trials,
    "sandwich_or_duality_violations": 0,
})
"""
        ),
        _markdown(
            r"""
## 5. Vanishing average reconstruction loss with fixed worst-case defect

For each support size `N`, two physical states `-1` and `+1` share a code and decode to zero; every
other state reconstructs exactly. Under the uniform distribution, mean squared reconstruction
error is `2/N`, yet the safe state at margin one remains exactly confounded with an unsafe state.
This finite family is a direct tail counterexample: an expected objective alone cannot control a
uniform fiber defect.
"""
        ),
        _code(
            r"""
support_sizes = np.asarray([4, 8, 16, 32, 64, 128, 256, 512, 1024, 2048])
average_losses = []
worst_defects = []
for size in support_sizes:
    physical_states = [-1.0, 1.0] + [float(10 + index) for index in range(size - 2)]
    model_codes = [(0.0,), (0.0,)] + [(float(index + 1),) for index in range(size - 2)]
    model_margins = [-1.0, 1.0] + [0.5] * (size - 2)
    decoded_states = [0.0, 0.0] + physical_states[2:]
    mse = np.mean([
        (state - decoded) ** 2
        for state, decoded in zip(physical_states, decoded_states, strict=True)
    ])
    defect = audit_finite_static_fibers(model_codes, model_margins).exact_defect
    average_losses.append(float(mse))
    worst_defects.append(defect)

assert np.allclose(average_losses, 2.0 / support_sizes)
assert set(worst_defects) == {1.0}
display({
    "smallest_average_loss": average_losses[-1],
    "defect_at_smallest_loss": worst_defects[-1],
    "support_size": int(support_sizes[-1]),
})
"""
        ),
        _markdown(
            r"""
### 5b. Smooth population construction with identity dynamics

The finite construction above can be dismissed as an atom of vanishing probability. The analytic
construction in Proposition 1 is stronger: a compactly supported C-infinity perturbation of the
identity maps the fixed states `-a` and `+a` to the same code, while the affected intervals shrink
with width `delta`. With identity decoder/dynamics/predictor, reconstruction MSE is `O(delta)` and
latent one-step prediction error is exactly zero. The conflicting action margins remain fixed.
"""
        ),
        _code(
            r"""
collision_margin = 0.4
widths = np.asarray([0.08, 0.04, 0.02, 0.01, 0.005])
quadrature_states = np.linspace(-1.0, 1.0, 40_001, endpoint=True)
smooth_mse = []
smooth_bounds = []
for width in widths:
    codes = np.asarray([
        localized_collision_encoder(
            float(state), collision_margin=collision_margin, width=float(width)
        )
        for state in quadrature_states
    ])
    smooth_mse.append(float(np.mean((quadrature_states - codes) ** 2)))
    smooth_bounds.append(localized_collision_mse_bound(
        collision_margin=collision_margin, width=float(width)
    ))
    assert np.isclose(localized_collision_encoder(
        collision_margin, collision_margin=collision_margin, width=float(width)
    ), 0.0)
    assert np.isclose(localized_collision_encoder(
        -collision_margin, collision_margin=collision_margin, width=float(width)
    ), 0.0)

smooth_action = audit_exact_action_fibers(
    [(0.0,), (0.0,)],
    [signed_action_margins(collision_margin), signed_action_margins(-collision_margin)],
)
assert np.all(np.asarray(smooth_mse) <= np.asarray(smooth_bounds) * 1.001)
assert smooth_action.conflicting_fiber_count == 1
assert np.isclose(smooth_action.worst_required_violation, collision_margin)

fig, axis = plt.subplots(figsize=(5.2, 3.6))
axis.loglog(widths, smooth_mse, marker="o", label="quadrature reconstruction MSE")
axis.loglog(widths, smooth_bounds, linestyle="--", label=r"analytic $2a^2\delta$ bound")
axis.set(xlabel="localized-fold width delta", ylabel="uniform reconstruction MSE")
axis.set_title("Smooth collision: mean loss vanishes, defect stays at 0.4")
axis.legend(frameon=False)
fig.tight_layout()
plt.show()

display({
    "smooth_encoder_collision_margin": collision_margin,
    "smallest_width": float(widths[-1]),
    "smallest_quadrature_mse": smooth_mse[-1],
    "analytic_bound_at_smallest_width": smooth_bounds[-1],
    "latent_identity_dynamics_prediction_mse": 0.0,
    "action_required_violation": smooth_action.worst_required_violation,
})
"""
        ),
        _markdown("## 6. Visual audit and theorem-check summary"),
        _code(
            r"""
fig, axes = plt.subplots(1, 2, figsize=(10.5, 3.8))
axes[0].loglog(support_sizes, average_losses, marker="o", label="mean reconstruction MSE")
axes[0].plot(support_sizes, worst_defects, marker="s", label="exact static defect")
axes[0].set(xlabel="uniform support size", ylabel="value")
axes[0].set_title("Average loss does not control the tail")
axes[0].legend(frameon=False)

axes[1].plot(q_action_zero, expected_by_state[0], label="state 0 expected margin")
axes[1].plot(q_action_zero, expected_by_state[1], label="state 1 expected margin")
axes[1].plot(q_action_zero, worst_expected_margin, color="black", linewidth=2, label="worst state")
axes[1].axhline(0.0, color="black", alpha=0.3, linestyle=":")
axes[1].set(xlabel="probability of action 0", ylabel="expected safety margin")
axes[1].set_title("Expectation differs from pointwise safety")
axes[1].legend(frameon=False, fontsize=8)
fig.tight_layout()
plt.show()

checks = {
    "static_equivalence_cases": frontier_cases,
    "data_processing_cases": data_processing_cases,
    "data_processing_violations": 0,
    "zero_endpoint_cases_distinguished": True,
    "action_conflict_detected": action_audit.conflicting_fiber_count == 1,
    "finite_action_lp_trials": finite_action_trials,
    "strong_randomized_equals_deterministic": hard_slacks[2] == hard_slacks[0],
    "average_loss_counterexample_verified": set(worst_defects) == {1.0},
    "smooth_population_counterexample_verified": bool(
        smooth_action.conflicting_fiber_count == 1
        and np.all(np.asarray(smooth_mse) <= np.asarray(smooth_bounds) * 1.001)
    ),
}
print(json.dumps(checks, indent=2, sort_keys=True))
"""
        ),
        _markdown(
            r"""
## Takeaways and proof obligations that remain

The finite oracles agree with brute-force certificate enumeration, and no counterexample to finite
data processing appeared in the exhaustive grid. The endpoint, randomization, and average-loss
examples should be retained as regression tests because each blocks a tempting overstatement.

This does **not** close the population theory. Remaining obligations include the treatment of
non-attained suprema, measurability/selection for positive action results, continuous action spaces,
uncountable fibers, approximate latent neighborhoods, and a certified way to compute population
violation scores. The source of novelty is also not the maximal pure-safe latent set itself; the
paper must distinguish its quantitative/action/partial-observability results from prior latent-safe
set work.
"""
        ),
    ]
    return _notebook(cells, experiment="Theory finite exhaustive checks")


def _dynamic_regret_oracle_notebook() -> nbf.NotebookNode:
    cells = [
        _markdown(
            r"""
# Dynamic regret oracle on two controlled domains

**TL;DR.** Complete registered three-step nominal action trees expose the same hidden-velocity
mechanism in both controlled domains. Privileged kinematic state and a two-frame observation-only
history retain the full-history Bellman value on every enumerated node. The identical current
frame has both positive optimal-margin regret `rho_3` and positive sign obstruction `kappa_3`:
every common action is unsafe for at least one viable root in both domains. These are exhaustive
finite floating-point checks at recorded tolerance, not learned-model evidence or a
population/deployment certificate.
"""
        ),
        _markdown(
            r"""
## Context & Methods

### Key assumptions

- Each tree contains two hand-selected roots, all three registered actions at every node, and all
  `3^3` deterministic nominal action sequences. Process noise is fixed to zero.
- A safe predecessor reaches each root algebraically under the nominal model. The roots were not
  sampled from the behavior-policy dataset; the cart speeds exceed its noise-free envelope.
- Safety is the worst current-state margin over the three-step path, with the closed convention
  `h >= 0`. The action set is finite and successors are singleton nominal transitions.
- Exact full-frame tuples are used directly as codes—no hashes or learned embeddings. Scene
  geometry has already been quantized by the configured 32-by-32 raster.
- `rho_s` is robust optimal-margin regret, not a safety defect. `kappa_s` separately measures
  first-action sign obstruction on viable fibers; global policy existence is checked by the
  finite common-safe-action Bellman characterization.
- Exact tuple equality and exhaustive branches do not imply exact arithmetic. Dynamics use binary
  floating point and trigonometry; all inequalities use the report's recorded tolerance.
- The result covers only the enumerated roots, horizon, action grid, and nominal dynamics. It does
  not cover the continuous population, Gaussian disturbances, model mismatch, or learned models.
"""
        ),
        _code(
            r"""
from pathlib import Path
import sys

import matplotlib.pyplot as plt
import numpy as np
from IPython.display import display

ROOT = Path.cwd()
if ROOT.name == "notebooks":
    ROOT = ROOT.parent
elif (ROOT / "LatentSafety" / "src").exists():
    ROOT = ROOT / "LatentSafety"
if not (ROOT / "src" / "latent_safety").exists():
    raise RuntimeError(f"Could not locate repository root from {Path.cwd()}")
sys.path.insert(0, str(ROOT / "src"))

from latent_safety.benchmarks.dynamic_oracle import (
    MEMORYLESS_PIXELS,
    PRIVILEGED_STATE,
    TWO_FRAME_HISTORY,
    audit_controlled_dynamic_oracle,
    build_controlled_dynamic_tree,
)
from latent_safety.learning import load_config

config_paths = {
    "cart": ROOT / "configs/e1_world_models/torch_pilot.toml",
    "pendulum": ROOT / "configs/e1_world_models/torch_pendulum_pilot.toml",
}
configs = {name: load_config(path).data for name, path in config_paths.items()}
trees = {
    name: build_controlled_dynamic_tree(config, horizon=3)
    for name, config in configs.items()
}
reports = {
    name: audit_controlled_dynamic_oracle(config, horizon=3)
    for name, config in configs.items()
}
print({
    "status": "finite_nominal_theorem_oracle_not_empirical_evidence",
    "domains": list(reports),
    "horizon": 3,
    "tolerances": {name: report.tolerance for name, report in reports.items()},
    "config_sha256": {name: report.config_sha256 for name, report in reports.items()},
    "training_support_status": {
        name: report.training_support_status for name, report in reports.items()
    },
    "repo_root": str(ROOT),
})
"""
        ),
        _markdown(
            r"""
## Data

### 1. Verify tree completeness and the intended fibers

With two roots, three actions, and horizon three, the layer counts from zero to three remaining
controls must be `(54, 18, 6, 2)`. Each nonterminal history-action pair has exactly one successor,
so this is exhaustive for the declared deterministic model. At the roots, the current-frame code
must merge both histories, while state and two-frame observation-only codes must separate them.
"""
        ),
        _code(
            r"""
tree_rows = []
for domain, tree in trees.items():
    remaining = tree.horizon
    roots = tree.root_histories
    code_counts = {
        representation: len({
            tree.codes_by_representation[representation][(remaining, root)]
            for root in roots
        })
        for representation in (
            PRIVILEGED_STATE,
            MEMORYLESS_PIXELS,
            TWO_FRAME_HISTORY,
        )
    }
    expected_successors = sum(
        len(tree.histories_by_remaining[step]) * len(tree.actions)
        for step in range(1, tree.horizon + 1)
    )
    tree_rows.append({
        "domain": domain,
        "node_count_by_remaining": tree.node_count_by_remaining,
        "total_histories": sum(tree.node_count_by_remaining),
        "successor_entries": len(tree.successors),
        "root_code_counts": code_counts,
        "fixture_version": tree.fixture_version,
        "config_sha256": tree.config_sha256,
        "population_certificate": tree.population_certificate,
    })
    assert tree.node_count_by_remaining == (54, 18, 6, 2)
    assert len(tree.successors) == expected_successors == 78
    assert code_counts[MEMORYLESS_PIXELS] == 1
    assert code_counts[PRIVILEGED_STATE] == 2
    assert code_counts[TWO_FRAME_HISTORY] == 2
    assert not tree.population_certificate

display(tree_rows)
"""
        ),
        _markdown(
            r"""
## Results

### 2. Stagewise regret, sign obstruction, retained viability, and bounds

`B_s` follows only successors reached by the constructed representation policy; the global bound
is the looser sum of maximum stage regrets. `delta_s*` is the finite midpoint error for
fiber/action Q ranges. `kappa_s > 0` means at least one viable fiber has no common safe first
action. The composition theorem requires `loss <= B <= global` and `rho <= 2 delta*`.
"""
        ),
        _code(
            r"""
stage_rows = []
for domain, report in reports.items():
    for representation in report.representations:
        for stage in representation.stages:
            row = {
                "domain": domain,
                "representation": representation.representation,
                "remaining_steps": stage.remaining_steps,
                "fibers": stage.fiber_count,
                "rho_s": stage.rho_s,
                "kappa_s": stage.kappa_s,
                "delta_s_star": stage.delta_s_star,
                "realized_loss": stage.max_realized_policy_loss,
                "max_B_s": stage.max_path_bound_B,
                "global_sum_bound": stage.global_sum_bound,
                "full_history_viable": stage.full_history_viable_count,
                "minimax_policy_retained": (
                    stage.selected_policy_retained_viable_count
                ),
                "minimax_policy_retained_fraction": (
                    stage.selected_policy_retained_viable_fraction
                ),
                "least_violating_policy_retained": (
                    stage.first_action_safety_policy_retained_viable_count
                ),
                "least_violating_policy_retained_fraction": (
                    stage.first_action_safety_policy_retained_viable_fraction
                ),
                "viable_fibers_without_common_safe_action": (
                    stage.fibers_without_common_safe_action
                ),
            }
            stage_rows.append(row)
            assert stage.rho_s <= 2.0 * stage.delta_s_star + report.tolerance
            assert stage.max_realized_policy_loss <= (
                stage.max_path_bound_B + report.tolerance
            )
            assert stage.max_path_bound_B <= (
                stage.global_sum_bound + report.tolerance
            )
        assert representation.theorem_bound_holds
        assert representation.closed_endpoint_holds
        assert representation.global_sign_characterization_holds

display(stage_rows)
"""
        ),
        _markdown(
            r"""
### 3. Separate optimal-margin regret from retained viability

The root table directly checks the sign of the optimal value `V` and representation-policy value
`J`. The root-fiber table separately exposes common safe actions and `kappa_3`. In both domains the
memoryless fiber contains two viable histories but has no common safe first action, which is
stronger than failure of the particular minimax-margin policy.
"""
        ),
        _code(
            r"""
root_rows = []
root_fiber_rows = []
summaries = {}
for domain, report in reports.items():
    for representation in report.representations:
        summaries[(domain, representation.representation)] = representation
        for outcome in representation.root_outcomes:
            root_rows.append({
                "domain": domain,
                "representation": representation.representation,
                "root": outcome.history_id,
                "V_optimal": outcome.optimal_value,
                "J_minimax_margin_policy": outcome.representation_policy_value,
                "J_least_violating_safety_policy": (
                    outcome.first_action_safety_policy_value
                ),
                "realized_loss": outcome.realized_policy_loss,
                "B": outcome.path_bound_B,
                "optimal_finite_horizon_viable": (
                    outcome.finite_horizon_viable_under_optimal_policy
                ),
                "minimax_policy_finite_horizon_viable": (
                    outcome.finite_horizon_viable_under_representation_policy
                ),
                "safety_policy_finite_horizon_viable": (
                    outcome.finite_horizon_viable_under_first_action_safety_policy
                ),
            })
        for fiber in representation.root_fiber_safety:
            root_fiber_rows.append({
                "domain": domain,
                "representation": representation.representation,
                "fiber_index": fiber.fiber_index,
                "histories": fiber.histories,
                "viable_histories": fiber.viable_histories,
                "common_safe_actions": fiber.common_safe_actions,
                "kappa_3": fiber.first_action_obstruction,
                "minimax_margin_action": fiber.optimal_margin_action,
                "least_violating_action": fiber.least_violating_safety_action,
                "exact_viability_preserving_policy_exists": (
                    representation.exact_viability_preserving_code_policy_exists
                ),
            })

cart_pixels = summaries[("cart", MEMORYLESS_PIXELS)]
pendulum_pixels = summaries[("pendulum", MEMORYLESS_PIXELS)]
for memoryless_summary in (cart_pixels, pendulum_pixels):
    root_stage = memoryless_summary.stages[-1]
    assert root_stage.kappa_s > 0.0
    assert root_stage.fibers_without_common_safe_action == 1
    assert memoryless_summary.root_fiber_safety[0].common_safe_actions == ()
    assert not memoryless_summary.exact_viability_preserving_code_policy_exists
    assert all(
        outcome.finite_horizon_viable_under_optimal_policy
        for outcome in memoryless_summary.root_outcomes
    )
for domain in reports:
    for representation in (PRIVILEGED_STATE, TWO_FRAME_HISTORY):
        summary = summaries[(domain, representation)]
        assert summary.exact_viability_preserving_code_policy_exists
        assert all(stage.kappa_s == 0.0 for stage in summary.stages)
        assert all(
            outcome.optimal_value == outcome.representation_policy_value
            for outcome in summary.root_outcomes
        )

display(root_rows)
display(root_fiber_rows)
"""
        ),
        _markdown("### 4. Visual check at the registered three-step horizon"),
        _code(
            r"""
labels = []
rho_values = []
kappa_values = []
delta_values = []
loss_values = []
bound_values = []
for domain in ("cart", "pendulum"):
    for representation, short_name in (
        (PRIVILEGED_STATE, "state"),
        (MEMORYLESS_PIXELS, "frame"),
        (TWO_FRAME_HISTORY, "history"),
    ):
        stage = summaries[(domain, representation)].stages[-1]
        labels.append(f"{domain}\n{short_name}")
        rho_values.append(stage.rho_s)
        kappa_values.append(stage.kappa_s)
        delta_values.append(stage.delta_s_star)
        loss_values.append(stage.max_realized_policy_loss)
        bound_values.append(stage.max_path_bound_B)

x = np.arange(len(labels))
width = 0.16
fig, axis = plt.subplots(figsize=(10.5, 4.2))
axis.bar(x - 2.0 * width, rho_values, width, label=r"$\rho_3$")
axis.bar(x - width, kappa_values, width, label=r"$\kappa_3$")
axis.bar(x, delta_values, width, label=r"$\delta_3^*$")
axis.bar(x + width, loss_values, width, label="realized loss")
axis.bar(x + 2.0 * width, bound_values, width, label=r"path bound $B_3$")
axis.set_xticks(x, labels)
axis.set_ylabel("robust margin units")
axis.set_title("Exhaustive three-step quantities on registered nominal trees")
axis.legend(frameon=False, ncols=5)
fig.tight_layout()
plt.show()
"""
        ),
        _markdown(
            r"""
## Takeaways

The finite oracle makes two distinct statements visible. Identical current pixels impose positive
robust optimal-margin regret in both dynamics. More strongly, each memoryless root fiber has
positive `kappa_3`: every common action is unsafe for at least one full-history-viable root. A
causal second frame alone removes both registered obstructions; no previous action is supplied.

This is a theorem/benchmark integration check, not a learned-representation result. It cannot be
used as paper evidence that an H4 neural encoder discovers velocity, nor as a population safety
certificate. The roots are constructed witnesses, not samples from the training distribution.
The next empirical question is whether trained history models reduce held-out
representation audits at matched world-model utility, with radii and model selection frozen on
validation data.
"""
        ),
    ]
    return _notebook(
        cells,
        experiment="Two-domain finite dynamic regret oracle",
        status="executed_finite_nominal_oracle_not_empirical_evidence",
    )


BUILDERS = {
    "00_e0_estimator_validation.ipynb": _e0_notebook,
    "01_e1_torch_world_model_pilot.ipynb": _e1_notebook,
    "02_theory_counterexamples.ipynb": _theory_notebook,
    "03_pilot_analysis_template.ipynb": _analysis_notebook,
    "04_two_domain_oracle_controls.ipynb": _two_domain_oracle_notebook,
    "05_dynamic_regret_oracle.ipynb": _dynamic_regret_oracle_notebook,
}


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "names",
        nargs="*",
        choices=tuple(BUILDERS),
        help="Notebook filenames to build (default: all).",
    )
    args = parser.parse_args()

    NOTEBOOK_DIR.mkdir(parents=True, exist_ok=True)
    selected = args.names or list(BUILDERS)
    for name in selected:
        path = NOTEBOOK_DIR / name
        nbf.write(BUILDERS[name](), path)
        print(f"built {path.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
